<script setup lang="ts">
type MockSim = { msisdn: string, iccid: string, status: string, label: string, offerId: string, description: string, benefitCount: number, balances: { data: number, voice: number, sms: number } }
const { data: sims, refresh } = await useFetch<MockSim[]>('/api/mock/sims')
const copied = ref(false)
const consuming = ref<string | null>(null)
async function copyBaseUrl () { await navigator.clipboard.writeText('http://localhost:3000'); copied.value = true; setTimeout(() => { copied.value = false }, 1800) }
async function resetFixtures () { await $fetch('/api/mock/reset', { method: 'POST' }); await refresh() }
async function consumeBalance (msisdn: string) { consuming.value = msisdn; try { await $fetch(`/api/mock/sims/${msisdn}/consume`, { method: 'POST' }); await refresh() } finally { consuming.value = null } }
useSeoMeta({ title: 'Altán local · API simulator', description: 'Simulador local de operaciones Altán para CRM.' })
</script>
<template>
  <section class="hero"><div class="eyebrow"><span class="pulse" /> Entorno de integración local</div><h1>Prueba el flujo,<br><em>no la red.</em></h1><p>Una réplica mínima de Altán para desarrollar activaciones, preactivaciones, compras, cambios de plan y consulta de perfil sin tocar una línea real.</p><div class="connection-card"><span>URL base para configurar en CRM</span><code>http://localhost:3000</code><button type="button" @click="copyBaseUrl">{{ copied ? 'Copiada' : 'Copiar URL' }}</button></div><div class="hero-notes"><span>6 endpoints disponibles</span><span>Estado en memoria</span><span>Fixtures reiniciables</span></div></section>
  <section id="sims" class="content-section"><div class="section-heading"><div><p class="eyebrow">SIMs de laboratorio</p><h2>Un número por escenario</h2></div><button class="quiet-button" type="button" @click="resetFixtures">Restaurar escenarios</button></div><p class="section-intro">El botón consume 250 MB, 60 minutos y 20 SMS. Refresca el perfil del CRM para observar las bolsas reducidas.</p><div class="sim-grid"><article v-for="sim in sims" :key="sim.msisdn" class="sim-card"><div class="sim-card-top"><span :class="['status-dot', sim.status === 'Active' ? 'active' : '']" />{{ sim.label }}</div><code>{{ sim.msisdn }}</code><p>{{ sim.description }}</p><div v-if="sim.benefitCount" class="balances"><span><b>{{ sim.balances.data }}</b> MB</span><span><b>{{ sim.balances.voice }}</b> min</span><span><b>{{ sim.balances.sms }}</b> SMS</span></div><button v-if="sim.benefitCount" class="consume-button" type="button" :disabled="consuming === sim.msisdn" @click="consumeBalance(sim.msisdn)">{{ consuming === sim.msisdn ? 'Consumiendo…' : 'Consumir saldo' }}</button><footer><span>Oferta {{ sim.offerId }}</span><span>{{ sim.iccid }}</span></footer></article></div></section>
  <section id="endpoints" class="content-section endpoints"><p class="eyebrow">Contrato compatible</p><h2>Endpoints expuestos</h2><div class="endpoint-list"><div><b class="post">POST</b><code>/v1/oauth/accesstoken</code><span>Token local</span></div><div><b class="get">GET</b><code>/cm/v1/subscribers/{msisdn}/profile</code><span>Perfil y estado</span></div><div><b class="post">POST</b><code>/cm/v1/subscribers/{msisdn}/activate</code><span>Activa una SIM Idle</span></div><div><b class="post">POST</b><code>/cm/v1/subscribers/{msisdn}/preregistered</code><span>Preactivación</span></div><div><b class="post">POST</b><code>/cm/v1/products/purchase</code><span>Compra / recarga</span></div><div><b class="patch">PATCH</b><code>/cm/v1/subscribers/{msisdn}</code><span>Cambio de plan</span></div></div></section>
  <section id="uso" class="content-section setup"><p class="eyebrow">Configuración CRM</p><h2>Selecciona <code>LOCAL</code> y pega las rutas.</h2><ol><li>Inicia este proyecto con <code>pnpm dev</code>.</li><li>En el CRM, selecciona el ambiente <code>LOCAL</code>.</li><li>Configura la URL base y habilita transacciones para ejecutar llamadas simuladas.</li></ol><p class="caution">El proceso no almacena información: una recarga, cambio de oferta o activación se descarta al reiniciar.</p></section>
</template>
